brew "bat"
brew "colordiff"
brew "cookiecutter"
brew "croc"
brew "curl"
brew "fx"
brew "fzf"
brew "gh"
brew "git", link: true
brew "git-lfs"
brew "htop"
brew "jq"
brew "make"
brew "ncdu"
brew "node"
brew "pandoc"
brew "python", link: true
brew "ruby", link: true
brew "shellcheck"
brew "tmux"
brew "vim", link: true
brew "watch"
brew "zsh", link: true

cask "docker"
cask "iterm2"
cask "mactex"
cask "spotify"
cask "vlc"
cask "zoom"
