brew "argo"
brew "bash", link: true
brew "bat"
brew "colordiff"
brew "cookiecutter"
brew "croc"
brew "curl"
brew "fd"
brew "ffmpeg"
brew "fx"
brew "fzf"
brew "gh"
brew "git", link: true
brew "git-lfs"
brew "helm"
brew "htop"
brew "jq"
brew "make"
brew "ncdu"
brew "pandoc"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python", link: true
brew "r"
brew "ripgrep"
brew "ruby", link: true
brew "shellcheck"
brew "tmux"
brew "vim", link: true
brew "zsh", link: true

cask "audacity" unless "[[ -n ${DOTFILES_FRONTEND} ]]"
cask "brave-browser" unless "[[ -n ${DOTFILES_FRONTEND} ]]"
cask "docker" unless "[[ -n ${DOTFILES_FRONTEND} ]]"
cask "iterm2" unless "[[ -n ${DOTFILES_FRONTEND} ]]"
cask "spotify" unless "[[ -n ${DOTFILES_FRONTEND} ]]"
cask "vlc" unless "[[ -n ${DOTFILES_FRONTEND} ]]"
cask "zoom" unless "[[ -n ${DOTFILES_FRONTEND} ]]"
