name: install
description: Install remotely from GitHub branch
runs:
  using: composite
  steps:
    - name: Download installer
      run: |
        echo "Installing from branch ${{ env.GITHUB_HEAD_REF }}"
        curl -fsSLO https://raw.githubusercontent.com/benjcunningham/dotfiles/${{ env.GITHUB_HEAD_REF }}/install.sh
      shell: bash
