name: "continuous-integration"

on:
  push:
    branches:
    - "master"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - "macos-latest"
          - "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Lint scripts with Shellcheck"
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        "sudo apt-get install shellcheck"
        "./test.sh"
    - name: "Execute full installation"
      run: "./install.sh"
