name: "documentation"

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:

    # Checkout codebase
    - uses: "actions/checkout@v2"

    # Build Sphinx docs
    - uses: "ammaraskar/sphinx-action@master"
      with:
        docs-folder: "docs/"

    # Create GitHub artifact from built HTML
    - uses: "actions/upload-artifact@v1"
      with:
        name: "DocumentationHTML"
        path: "docs/build/html"

    # Commit HTML to gh-pages branch
    - name: "Commit to GitHub Pages"
      run: |
        git clone https://github.com/benjcunningham/dotfiles.git --branch gh-pages --single-branch gh-pages
        cp -r docs/build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "🤖📝" -a || true

    # Push gh-pages to remote
    - name: "Push to GitHub Pages"
      uses: "ad-m/github-push-action@master"
      with:
        branch: "gh-pages"
        directory: "gh-pages"
        github_token: ${{ secrets.GITHUB_TOKEN }}
