name: full
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
    steps:
    - name: Installation
      run: |
        GITHUB_BRANCH=${GITHUB_REF#refs/heads/}
        echo "Installing from branch $GITHUB_BRANCH"
        curl -fsSLO https://raw.githubusercontent.com/benjcunningham/dotfiles/$GITHUB_BRANCH/install.sh
        bash install.sh -pw
