name: lint

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string

jobs:
  lint:
    runs-on: ${{ inputs.runs-on }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build and test image
      run: make test/lint SYSTEM_TARGET=${{ inputs.runs-on }}
