name: macos
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  install:
    runs-on: macos-12
    steps:
    - name: Unlink GitHub virtual environment Git
      run: brew unlink git@2.35.1
    - uses: actions/checkout@v3
      with:
        path: branch
    - uses: ./branch/.github/actions/environment
    - uses: ./branch/.github/actions/install
      with:
        install-args: -pw
