name: macos
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  install:
    runs-on: macos-12
    steps:
    - uses: .github/actions/environment
    - name: Unlink GitHub virtual environment Git
      run: brew unlink git@2.35.1
    - uses: .github/actions/install
      with:
        install-args: -pw
