name: macos
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  install-full:
    runs-on: macos-latest
    steps:
    - name: Set branch ref
      shell: bash
      run: |
        echo "GITHUB_HEAD_REF=${GITHUB_HEAD_REF:-master}" >> $GITHUB_ENV
    - name: Install from remote
      run: |
        echo "Installing from branch ${{ env.GITHUB_HEAD_REF }}"
        curl -fsSLO https://raw.githubusercontent.com/benjcunningham/dotfiles/${{ env.GITHUB_HEAD_REF }}/install.sh
        bash install.sh -pw
