name: minimal
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
    - name: Installation
      run: |
        echo "Installing from branch $GITHUB_HEAD_REF"
        curl -fsSLO https://raw.githubusercontent.com/benjcunningham/dotfiles/$GITHUB_HEAD_REF/install.sh
        bash install.sh -m
