name: ubuntu

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      install-args:
        required: true
        type: string

jobs:
  install:
    runs-on: ${{ inputs.runs-on }}
    steps:
    - name: Checkout repository (for actions only)
      uses: actions/checkout@v3
      with:
        path: branch
    - name: Setup CI environment
      uses: ./branch/.github/actions/environment
    - name: Download and run remote install script
      uses: ./branch/.github/actions/install
      with:
        install-args: ${{ inputs.install-args }}
