name: ubuntu
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  quality:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
    - name: Verify code quality
      run: ./test.sh
  install:
    needs:
    - quality
    runs-on: ubuntu-20.04
    steps:
    - uses: ./.github/actions/environment
    - uses: ./.github/actions/install
      with:
        install-args: -pw
