name: ubuntu
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install linter dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
    - name: Run linters
      run: ./test.sh
  install:
    needs:
    - lint
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository (for actions only)
      uses: actions/checkout@v3
      with:
        path: branch
    - name: Setup CI environment
      uses: ./branch/.github/actions/environment
    - name: Download and run remote install script
      uses: ./branch/.github/actions/install
      with:
        install-args: -pw
